kind: pipeline
name: default

steps:
  - name: build
    image: dvitali/builder-tools:latest
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - ls -la
      - bash ./build.sh
      - bash ./build.sh -e
