kind: pipeline
name: default

steps:
  - name: build
    image: dvitali/builder-tools:latest
    privileged: true
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - bash ./build.sh
      - bash ./build.sh -e
